name: Continuous Integration

on:
  push:
    branches:
    - master

jobs:
  pushUpm:
    name: Publish UPM
    needs: testAllModes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: push to UPM branch
        run: |
          git subtree push --prefix "$PKG_ROOT" origin upm
        env:
          PKG_ROOT: Assets/i5 Toolkit for Unity